wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1654734086
    t:
      1:
      - 1
      - 9
      - 40
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
callbacks:
  desc: null
  value:
  - lib: src.utils
    name: WandBCallback
    params:
      labels:
      - no 3
      - '3'
datamodule:
  desc: null
  value:
    batch_size: 32
    path: dataset
logger:
  desc: null
  value: WandbLogger
logger_params:
  desc: null
  value:
    name: '006'
    project: dlops-mnist
trainer:
  desc: null
  value:
    enable_checkpointing: false
    logger: true
    max_epochs: 10
    overfit_batches: 0
