callbacks: null
datamodule:
  batch_size: 32
  path: !!python/object/apply:pathlib.PosixPath
  - dataset
logger: WandbLogger
logger_params:
  name: '004'
  project: dlops_portfolio_mnist
trainer:
  enable_checkpointing: false
  logger: true
  max_epochs: 10
  overfit_batches: 0
