wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    python_version: 3.7.13
    start_time: 1654736048
    t:
      1:
      - 1
      - 9
      - 40
      - 41
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.7.13
      5: 0.12.17
      8:
      - 5
callbacks:
  desc: null
  value: None
datamodule:
  desc: null
  value:
    batch_size: 32
    path: dataset
datamodule/batch_size:
  desc: null
  value: 32
datamodule/path:
  desc: null
  value: dataset
logger:
  desc: null
  value: WandbLogger
logger_params:
  desc: null
  value:
    name: '101'
    project: dlops_portfolio_mnist
logger_params/name:
  desc: null
  value: '101'
logger_params/project:
  desc: null
  value: dlops_portfolio_mnist
trainer:
  desc: null
  value:
    enable_checkpointing: false
    logger: true
    max_epochs: 10
    overfit_batches: 0
trainer/enable_checkpointing:
  desc: null
  value: false
trainer/logger:
  desc: null
  value: true
trainer/max_epochs:
  desc: null
  value: 10
trainer/overfit_batches:
  desc: null
  value: 0
